const SPREADSHEET = new Spreadsheet('SHEET_ID')
const PATIENTS_SHEET = new Sheet(SPREADSHEET, 'PATIENTS_SHEET')
const PATIENTS_DATA_SHEET = new Sheet(SPREADSHEET, 'PATIENTS_DATA_SHEET')
const VISITS_SHEET = new Sheet(SPREADSHEET, 'VISITS_SHEET')
